### ISSUE TITLE
Still duplicate entries in staking page

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-indexer#1069]

**Comment by n1tranquilla** [comment]
This is causing FE unit tests to fail: https://buildkite.com/granola/mina-block-explorer/builds/1539#018fe98a-c102-47b3-aefa-211fbe1d26cf

After investigation, I found that the issue of this ticket is the root cause.

**Comment by robinbb** [comment]
Previously, until yesterday, for a few days, there were incorrectly-labeled staking ledgers in the staking ledgers directory. This happened because I thought that the ME staking ledgers were incorrectly labeled, so I "fixed" them. When I realized my mistake, I put the new, corrected staking ledgers in place, but forget to remove the old ones from the bucket. So, there would have been 2 different files both with the staking ledger number for each of 1, 2, and 3. I don't know if this caused this caused this issue's problem or not, but I'm making you aware. Please verify that it is still a problem.

**Comment by robinbb** [comment]
Issue resolved.
