### ISSUE TITLE
Indexer performance is degraded while new deployment is ongoing

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-indexer#1216]
The deployment of a new indexer (`n + 1`) is a long process, during which the performance of the existing indexer (`n`) is degraded. This creates a blocker for the front end CI systems.

**Comment by Isaac-DeFrain** [comment]
Is this still an issue?

**Comment by robinbb** [comment]
I think that the issue is that, during a prod deployment, the database is being built from scratch (sometimes). During that time, performance is degraded.

This is really an issue to monitor the progress of improvements: (1) using database snapshots for deployment, and (2) the startup time between when the server is started, and when it is actually ready. So, multiple issues underlying this user-visible issue.

**Comment by robinbb** [comment]
This is resolved. We now do not take down the running 'prod' instance until the new prod instance is ready to go, with a pre-generated database. We still do not use snapshots, however. The (2) mentioned above is now an acceptably low 20-ish seconds, because the database itself tends to have no log files to recover and because the shutdown of the prior instance tends to be clean (but not guaranteed to be so).
