### ISSUE TITLE
Problem: constants in `src/lib.rs` should be in its own file

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-indexer#372]
Refactor constants out of `src/lib.rs`

**Comment by robinbb** [comment]
This "problem" merits further explanation about why it is a problem, IMHO, if only another sentence or so. I think that we need another level of "why" in this problem, in other words. (Adding "because that is what is expected in Rust projects" might be sufficient, if that were indeed the "why" that underlies this problem.)
